### ISSUE TITLE
Storage should likely be an unsafe trait.

### ISSUE THREAD

**Issue by RustyYato** [timothee-haudebourg/raw-btree-rs#1]
```
pub trait Storage<T>: Default {
```

Because otherwise the implementor doesn't need to respect the post-conditions of any of the methods. Making the method unsafe doesn't help here, since unsafe methods only 8npose an obligation on the caller. 

For example, it would be entirely correct for Rust to allow implementing unsafe trait functions with safe functions. (In fact this has been proposed before!)

**Comment by timothee-haudebourg** [comment]
You're right, it should be unsafe.
